markdown: rdiscount
highlighter: pygments
permalink: /:year/:month/:day/:title.html
name: "HABIT IS POWER"

author: "linyehui"
atom-baseurl: "http://linyehui.github.io"
disqus: "linyehui"

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Blogroll
    class: fa fa-link
    href: /links.html
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml

